backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "services"
    label: "الخدمات"
    folder: "content/services"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "اسم الخدمة", name: "title", widget: "string" }
      - { label: "الوصف", name: "body", widget: "text" }
      - { label: "السعر", name: "price", widget: "string" }
      - { label: "صورة", name: "image", widget: "image" }
